---
version: 2
updates:
- package-ecosystem: bundler
  directory: "/backend"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 100
  registries: "*"
  insecure-external-code-execution: allow
  allow:
  - dependency-type: "all" # Allow both direct and indirect updates
